### ISSUE TITLE
RPi 3 compatible?

### ISSUE THREAD

**Issue by geotheory** [garthvh/pitftmenu#2]
Hi there. Is this compatible with the 3? Also with 3.5" Plus PiTFT?

**Comment by garthvh** [comment]
Works great on a Pi 3, the 3.5 plus has the same 480X320 resolution as the screen I have so it should work fine.

**Comment by geotheory** [comment]
Awesome I'll try it out

**Comment by garthvh** [comment]
Works fine with a Pi3
