### ISSUE TITLE
run with python3?

### ISSUE THREAD

**Issue by homeauto** [garthvh/pitftmenu#7]
Are you gonna update this so it will run on python3?

**Comment by garthvh** [comment]
Probably a good point, I will take a look this weekend

**Comment by homeauto** [comment]
Any lucky make this run on python3?

**Comment by garthvh** [comment]
ran a python converter called 2to3 against the python files in the project, have not tested.

**Comment by garthvh** [comment]
Tested on ubuntu with python 3.8
